zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  #image: wurstmeister/kafka:0.8.2.0
  build: .
  ports:
    - "9092:9092"
    - "9998:9998"
    - "9999:9999"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
